export default {
  TOKEN_SWAP_WIDGET_INITIALISED: 'TOKEN_SWAP_WIDGET_INITIALISED',
  TOKEN_SWAP_WIDGET_CLOSED: 'TOKEN_SWAP_WIDGET_CLOSED',
  TOKEN_SWAP_TRANSACTION_SUCCESSFUL: 'TOKEN_SWAP_TRANSACTION_SUCCESSFUL',
  TOKEN_SWAP_TRANSACTION_FAILED: 'TOKEN_SWAP_TRANSACTION_FAILED',
};
